# Generated by Django 4.0.4 on 2023-03-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq', models.IntegerField()),
                ('pk_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='Email')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.priority')),
            ],
        ),
    ]
