# Generated by Django 4.0.4 on 2023-03-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_info',
            name='priority',
        ),
        migrations.AddField(
            model_name='admin_info',
            name='priorityq',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='admin_info',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
