# Generated by Django 4.0.4 on 2023-03-24 16:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(null=True, upload_to='images_uploaded')),
                ('audio', models.FileField(null=True, upload_to='audios_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
            ],
        ),
    ]
